### PR TITLE
Added validation for purchase date field

### PR DESCRIPTION
**Pull request by MikeLenoir**

### CODE REVIEW

**Comment by abhinavsharma629** [comment]
The Validations are actually useless over here. A better idea is to put a date picker in the HTML file.
Besides the min allow date should be the time from which the user created the account and not 1900. That's inappropriate too.

**Comment by drewwmercer** [comment]
A user could create an account today and want to log their past maintenance, I don't think it should be limited to account date.

**Comment by MikeLenoir** [comment]
@drewwmercer would you like me to replace my code with a date picker or how would you like me to modify my original PR in some way?

**Comment by abhinavsharma629** [comment]
@drewwmercer I have a lot of ideas going on in my mind regarding this project, but I tried a lot to run it on my system, but running node server.js is closing without giving any errors and server doesn't run. Can you help me out with it, please?

**Comment by drewwmercer** [comment]
@abhinavsharma629 we have issue #96 open to hopefully address the setup troubleshooting

**Comment by abhinavsharma629** [comment]
Okay, sir @drewwmercer

**Pull request merged**
